version: '3.1'

services:
  redis_master:
    image: redis:latest
    restart: always
    container_name: redis_master
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
      - ./data:/data