version: "3"

services:
  mysql_server_003_single:
    image: mysql:8.0.29
    container_name: mysql_server_003_single
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_003_single/data:/var/data/mysql
      - /data/mysql_server_003_single/log:/var/log/mysql
      - /data/mysql_server_003_single/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50003:3306"
      - "53003:33060"
    networks:
      default:
        ipv4_address: 172.19.50.3

networks:
  default:
    external:
      name: docker_network