version: '2'

services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - 19091:19091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.18.90.91:29091,OUTSIDE://116.85.13.36:19091
      KAFKA_LISTENERS: INSIDE://:29091,OUTSIDE://:19091
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.156:12181,10.255.0.156:12182,10.255.0.156:12183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka1/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.91

  kafka2:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.18.90.92:29092,OUTSIDE://116.85.13.36:19092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:19092
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.156:12181,10.255.0.156:12182,10.255.0.156:12183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka2/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.92

  kafka3:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 19093:19093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.18.90.93:29093,OUTSIDE://116.85.13.36:19093
      KAFKA_LISTENERS: INSIDE://:29093,OUTSIDE://:19093
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.156:12181,10.255.0.156:12182,10.255.0.156:12183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka3/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.93

networks:
  br17218:
    external:
      name: br17218