version: "3"

services:
  mysql_server_006_slave0:
    image: mysql:8.0.29
    container_name: mysql_server_006_slave0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_006_slave0/data:/var/data/mysql
      - /data/mysql_server_006_slave0/log:/var/log/mysql
      - /data/mysql_server_006_slave0/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50123:3306"
      - "53123:33060"
    networks:
      default:
        ipv4_address: 172.19.50.123

networks:
  default:
    external:
      name: docker_network