version: '3.7'
services:
  kafka1001:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: unless-stopped
    hostname: kafka1001
    container_name: kafka1001
    ports:
      - "59091:9092"
      - "59092:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://10.255.0.229:59091,OUTSIDE://116.85.42.54:59092
      KAFKA_LISTENERS: INSIDE://:59091,OUTSIDE://:59092
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.108:52181,10.255.0.18:52181,10.255.0.229:52181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./logs:/kafka
    networks:
      default:
        ipv4_address: 172.18.0.10
networks:
  default:
    external:
      name: kafka_network
      