version: '2'

services:
  broker1:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: unless-stopped
    hostname: broker1
    container_name: broker1
    ports:
      - "59020:9092"
      - "59030:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://10.255.0.82:59020,OUTSIDE://116.85.49.74:59030
      KAFKA_LISTENERS: INSIDE://:59020,OUTSIDE://:59030
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.248:59010,10.255.0.248:59011,10.255.0.248:59012
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka1/logs:/kafka
    networks:
      default:
        ipv4_address: 172.19.0.15

  broker2:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: unless-stopped
    hostname: broker2
    container_name: broker2
    ports:
      - "59021:9092"
      - "59031:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://10.255.0.82:59021,OUTSIDE://116.85.49.74:59031
      KAFKA_LISTENERS: INSIDE://:59021,OUTSIDE://:59031
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.248:59010,10.255.0.248:59011,10.255.0.248:59012
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka2/logs:/kafka
    networks:
      default:
        ipv4_address: 172.19.0.16

  broker3:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: unless-stopped
    hostname: broker3
    container_name: broker3
    ports:
      - "59022:9092"
      - "59032:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://10.255.0.82:59022,OUTSIDE://116.85.49.74:59032
      KAFKA_LISTENERS: INSIDE://:59022,OUTSIDE://:59032
      KAFKA_ZOOKEEPER_CONNECT: 10.255.0.248:59010,10.255.0.248:59011,10.255.0.248:59012
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka3/logs:/kafka
    networks:
      default:
        ipv4_address: 172.19.0.17

networks:
  default:
    external:
      name: zookeeper_kafka