version: '3.4'
services:
  nodes_58001:
    image: redis:latest
    container_name: nodes_58001
    restart: always
    ports:
      - "58001:58001"
    volumes:
      - /home/nodes/redis_58001.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.11
  
  nodes_58002:
    image: redis:latest
    container_name: nodes_58002
    restart: always
    ports:
      - "58002:58002"
    volumes:
      - /home/nodes/redis_58002.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.12
  
  nodes_58003:
    image: redis:latest
    container_name: nodes_58003
    restart: always
    ports:
      - "58003:58003"
    volumes:
      - /home/nodes/redis_58003.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.13
  
  nodes_58004:
    image: redis:latest
    container_name: nodes_58004
    restart: always
    ports:
      - "58004:58004"
    volumes:
      - /home/nodes/redis_58004.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.14
  
  nodes_58005:
    image: redis:latest
    container_name: nodes_58005
    restart: always
    ports:
      - "58005:58005"
    volumes:
      - /home/nodes/redis_58005.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.15
  
  nodes_58006:
    image: redis:latest
    container_name: nodes_58006
    restart: always
    ports:
      - "58006:58006"
    volumes:
      - /home/nodes/redis_58006.conf:/etc/redis.conf
      - /home/nodes/timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: redis-server /etc/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.16

networks:
  default:
    external:
      name: docker_network