version: '3.4'

services:
  node_7001:
    image: xiaonian/redis:2.0.1
    container_name: node_7001
    restart: always
    ports:
      - "57001:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.11

  node_7002:
    image: xiaonian/redis:2.0.1
    container_name: node_7002
    restart: always
    ports:
      - "57002:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.12

  node_7003:
    image: xiaonian/redis:2.0.1
    container_name: node_7003
    restart: always
    ports:
      - "57003:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.13

  node_7004:
    image: xiaonian/redis:2.0.1
    container_name: node_7004
    restart: always
    ports:
      - "57004:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.14

  node_7005:
    image: xiaonian/redis:2.0.1
    container_name: node_7005
    restart: always
    ports:
      - "57004:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.15

  node_7006:
    image: xiaonian/redis:2.0.1
    container_name: node_7006
    restart: always
    ports:
      - "57004:7001"
    volumes:
      - ./node-7001/redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
    networks:
      default:
        ipv4_address: 172.19.0.16

networks:
  default:
    external:
      name: docker_network