version: '3.4'

services:
  redis_cluster_7001:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7001
    restart: always
    ports:
      - "57001:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.11
    networks:
      default:
        ipv4_address: 172.19.0.11

  redis_cluster_7002:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7002
    restart: always
    ports:
      - "57002:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.12
    networks:
      default:
        ipv4_address: 172.19.0.12

  redis_cluster_7003:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7003
    restart: always
    ports:
      - "57003:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.13
    networks:
      default:
        ipv4_address: 172.19.0.13

  redis_cluster_7004:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7004
    restart: always
    ports:
      - "57004:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.14
    networks:
      default:
        ipv4_address: 172.19.0.14

  redis_cluster_7005:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7005
    restart: always
    ports:
      - "57005:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.15
    networks:
      default:
        ipv4_address: 172.19.0.15

  redis_cluster_7006:
    image: xiaonian/redis:2.0.1
    container_name: redis_cluster_7006
    restart: always
    ports:
      - "57006:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled yes --cluster-announce-ip 172.19.0.16
    networks:
      default:
        ipv4_address: 172.19.0.16

networks:
  default:
    external:
      name: docker_network