version: "3"

services:
  redis_server_001:
    image: redis:7.0.11
    container_name: redis_server_001
    restart: always
    environment:
      - TZ=Asia/Shanghai # 设置时区
    volumes: # 配置数据卷
      - /data/redis_server_001/data:/data
      - /data/redis_server_001/conf/redis.conf:/etc/redis/redis.conf
    ports: # 映射端口
      - "6379:6379"
    sysctls: # 设置容器中的内核参数
      - net.core.somaxconn=1024
    command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
             && redis-server /etc/redis/redis.conf --appendonly yes" # 指定配置文件并开启持久化
    privileged: true
    networks:
      default:
        ipv4_address: 172.19.3.10

networks:
  default:
    external:
      name: docker_network