version: '2'

services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka1
    container_name: kafka1
    ports:
      - 19091:19091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://117.51.142.112:19091
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19091
      KAFKA_ZOOKEEPER_CONNECT: 117.51.142.112:12181,117.51.142.112:12182,117.51.142.112:12183
    volumes:
      - ./kafka1/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.91

  kafka2:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://117.51.142.112:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
      KAFKA_ZOOKEEPER_CONNECT: 117.51.142.112:12181,117.51.142.112:12182,117.51.142.112:12183
    volumes:
      - ./kafka2/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.92

  kafka3:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 19093:19093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://117.51.142.112:19093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19093
      KAFKA_ZOOKEEPER_CONNECT: 117.51.142.112:12181,117.51.142.112:12182,117.51.142.112:12183
    volumes:
      - ./kafka3/logs:/kafka
    external_links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      br17218:
        ipv4_address: 172.18.90.93

networks:
  br17218:
    external:
      name: br17218