version: "3"

services:
  demo_server_php_swoole_chat_register:
    image: php-swoole-8048:2.0.0
    container_name: demo_server_php_swoole_chat_register
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_php_swoole_chat/www:/data/www
    ports:
      - "50100:1236"
    command: /bin/bash -c "sh run_register.sh"
    networks:
      default:
        ipv4_address: 172.19.16.10
  demo_server_php_swoole_chat_worker:
    image: php-swoole-8048:2.0.0
    container_name: demo_server_php_swoole_chat_worker
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_php_swoole_chat/www:/data/www
    command: /bin/bash -c "sh run_worker.sh"
    networks:
      default:
        ipv4_address: 172.19.16.11
  demo_server_php_swoole_chat_gateway:
    image: php-swoole-8048:2.0.0
    container_name: demo_server_php_swoole_chat_gateway
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_php_swoole_chat/www:/data/www
    ports:
      - "50101:7272"
    command: /bin/bash -c "sh run_gateway.sh"
    networks:
      default:
        ipv4_address: 172.19.16.12
networks:
  default:
    external:
      name: docker_network