version: "3"

services:
  mysql_server_005:
    image: mysql:8.0.29
    container_name: mysql_server_005
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_005/data:/var/data/mysql
      - /data/mysql_server_005/log:/var/log/mysql
      - /data/mysql_server_005/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50102:3306"
      - "50302:33060"
    networks:
      default:
        ipv4_address: 172.19.50.102

networks:
  default:
    external:
      name: docker_network