version: "3"

services:
  demo_server_apache_php_7400:
    image: php-apache-7400:2.0.0
    container_name: demo_server_apache_php_7400
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_apache_php_7400/apache-config/httpd.conf:/etc/httpd/conf/httpd.conf
      - /data/demo_server_apache_php_7400/apache-logs:/etc/httpd/logs
      - /data/demo_server_apache_php_7400/www:/var/www/html
    ports:
      - "58801:80"
    networks:
      default:
        ipv4_address: 172.19.5.10

networks:
  default:
    external:
      name: docker_network