version: "3"

services:
  mysql_server_002_single:
    image: mysql:5.7.32
    container_name: mysql_server_002_single
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_002_single/data:/var/data/mysql
      - /data/mysql_server_002_single/log:/var/log/mysql
      - /data/mysql_server_002_single/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50002:3306"
      - "53002:33060"
    networks:
      default:
        ipv4_address: 172.19.50.2

networks:
  default:
    external:
      name: docker_network