version: "3"

services:
  mysql_server_004_master:
    image: mysql:8.0.29
    container_name: mysql_server_004_master
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_004_master/data:/var/data/mysql
      - /data/mysql_server_004_master/log:/var/log/mysql
      - /data/mysql_server_004_master/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50100:3306"
      - "53100:33060"
    networks:
      default:
        ipv4_address: 172.19.50.100

networks:
  default:
    external:
      name: docker_network