version: "3"

services:
  mysql_server_50741:
    image: mysql:5.7.41
    container_name: mysql_server_50741
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_50741/data:/var/data/mysql
      - /data/mysql_server_50741/log:/var/log/mysql
      - /data/mysql_server_50741/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50001:3306"
      - "53001:33060"
    networks:
      default:
        ipv4_address: 172.19.50.41

networks:
  default:
    external:
      name: docker_network