version: '3.1'

services:
  mysql_master:
    image: mysql:8.0.21
    restart: always
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 53300:3306
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/