version: '3.4'

services:
  redis_master_8000:
    image: xiaonian/redis:2.0.1
    container_name: redis_master_8000
    restart: always
    ports:
      - "58000:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled no
    networks:
      default:
        ipv4_address: 172.19.0.30

  redis_master_8001:
    image: xiaonian/redis:2.0.1
    container_name: redis_master_8001
    restart: always
    ports:
      - "58001:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled no
    networks:
      default:
        ipv4_address: 172.19.0.31

  redis_master_8002:
    image: xiaonian/redis:2.0.1
    container_name: redis_master_8002
    restart: always
    ports:
      - "58002:6379"
    volumes:
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf --cluster-enabled no
    networks:
      default:
        ipv4_address: 172.19.0.32

networks:
  default:
    external:
      name: docker_network