version: '3.4'
services:
  nodes_58001:
    image: redis:latest
    container_name: nodes_58001
    restart: always
    environment:
      - logfile=/data/redis.log
      - dir=/data
    command: redis-server /data/redis.conf
    ports:
      - 58001:58001
    volumes:
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./redis.conf:/data/redis.conf