version: '3.4'
services:
  nodes_58001:
    image: redis:latest
    container_name: nodes_58001
    restart: always
    environment:
      - logfile=/data/redis.log
      - dir=/data
      - protected-mode=no
      - appendonly=yes
      - cluster-enabled=yes
      - cluster-config-file=nodes-58001.conf
      - cluster-node-timeout=5000
      - cluster-announce-ip=112.74.58.15
      - cluster-announce-port=58001
      - cluster-announce-bus-port=57001
    command: redis-server
    ports:
      - 58001:6379
    volumes:
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime