version: "3"

services:
  mysql_server_006_slave1:
    image: mysql:8.0.29
    container_name: mysql_server_006_slave1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/mysql_server_006_slave1/data:/var/data/mysql
      - /data/mysql_server_006_slave1/log:/var/log/mysql
      - /data/mysql_server_006_slave1/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "50124:3306"
      - "53124:33060"
    networks:
      default:
        ipv4_address: 172.19.50.124

networks:
  default:
    external:
      name: docker_network