version: '3.1'

services:          
  mysql_slave1:
    image: mysql:8.0.21
    restart: always
    container_name: mysql_slave1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 53001:3306
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/