version: "3"

services:
  gitbit_server:
    image: gitblit/gitblit:latest
    container_name: gitbit_server
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/gitbit_server/data:/var/opt/gitblit
    command: ' --httpsPort=0'
    ports:
      - "58080:8080"
    networks:
      default:
        ipv4_address: 172.19.58.80

networks:
  default:
    external:
      name: docker_network