version: '2'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "59000:9000"
    environment:
      ZK_HOSTS: 10.255.0.108:52181,10.255.0.18:52181,10.255.0.229:52181
      TZ: Asia/Shanghai
    networks:
      default:
        ipv4_address: 172.17.0.10
networks:
  default:
    external:
      name: manager_network