version: '3.1'

services:
  wr_server:
    image: xioanian/mycat:1.6.7.5
    restart: always
    container_name: wr_container
    ports:
      - 58066:8066
      - 59066:9066
    volumes:
      - ./config/server.xml:/mycat/conf/server.xml:ro
      - ./config/schema.xml:/mycat/conf/schema.xml:ro
      - ./logs/:/mycat/logs/:rw