version: '3.4'
services:
  nodes-58001:
    image: redis:latest
    container_name: nodes-58001
    restart: always
    environment:
      - logfile=/data/redis.log
      - dir=/data
      - cluster-enabled=yes
      - cluster-config-file=nodes-58001.conf
      - cluster-node-timeout=5000
      - cluster-announce-ip=112.74.58.15
      - cluster-announce-port=58001
      - cluster-announce-bus-port=68001
    command: redis-server
    ports:
      - 58001:6379
    volumes:
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
   nodes-58002:
    image: redis:latest
    container_name: nodes-58002
    restart: always
    environment:
      - logfile=/data/redis.log
      - dir=/data
      - cluster-enabled=yes
      - cluster-config-file=nodes-58002.conf
      - cluster-node-timeout=5000
      - cluster-announce-ip=112.74.58.15
      - cluster-announce-port=58002
      - cluster-announce-bus-port=68002
    command: redis-server
    ports:
      - 58002:6379
    volumes:
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
  nodes-58003:
    image: redis:latest
    container_name: nodes-58003
    restart: always
    environment:
      - logfile=/data/redis.log
      - dir=/data
      - cluster-enabled=yes
      - cluster-config-file=nodes-58003.conf
      - cluster-node-timeout=5000
      - cluster-announce-ip=112.74.58.15
      - cluster-announce-port=58003
      - cluster-announce-bus-port=68003
    command: redis-server
    ports:
      - 58003:6379
    volumes:
      - ./timezone:/etc/timezone
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime