version: "3"

services:
  server_elasticsearch_head:
    image: tobias74/elasticsearch-head:latest
    container_name: server_elasticsearch_head
    environment:
      - TZ="Asia/Shanghai"
    restart: always
    ports:
      - "9100:9100"
    privileged: true
    networks:
      default:
        ipv4_address: 172.19.91.1

networks:
  default:
    external:
      name: docker_network