version: "3"

networks:
  gitea:
    external: false

services:
  gitea_server:
    image: gitea/gitea:1.16.8
    container_name: gitea_server
    environment:
      - USER_UID=root
      - USER_GID=root
      - DB_TYPE=mysql
      - DB_HOST=192.168.91.129:53306
      - DB_NAME=gitea
      - DB_USER=root
      - DB_PASSWD=xn9981k%
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "53000:3000"
      - "10022:22"