version: "3"

services:
  demo_server_redis_705:
    image: redis:7.0.2
    container_name: demo_server_redis_702
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_redis_705/config/redis.conf:/www/redis/redis.conf
      - /data/demo_server_redis_705/runtime/:/www/redis/runtime/
      - /data/demo_server_redis_705/data/:/www/redis/data/
    command: ["redis-server","/www/redis/redis.conf"]
    ports:
      - "56379:6379"
    networks:
      default:
        ipv4_address: 172.19.11.10

networks:
  default:
    external:
      name: docker_network