version: "3"

services:
  demo_server_php_swoole_tcp:
    image: php-swoole-8048:2.0.0
    container_name: demo_server_php_swoole_tcp
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_php_swoole_tcp/www:/data/www
    ports:
      - "59502:9502"
    command: /bin/bash -c "php server_tcp.php"
    networks:
      default:
        ipv4_address: 172.19.10.12

networks:
  default:
    external:
      name: docker_network