version: '3.1'

services:
  partition_server:
    image: xioanian/mycat:1.6.7.5
    restart: always
    container_name: partition_container
    ports:
      - 58061:8066
      - 59061:9066
    volumes:
      - ./config/server.xml:/mycat/conf/server.xml:ro
      - ./config/schema.xml:/mycat/conf/schema.xml:ro
      - ./config/rule.xml:/mycat/conf/rule.xml:ro
      - ./config/partition-range-mod.txt:/mycat/conf/partition-range-mod.txt:ro
      - ./config/autopartition-long.txt:/mycat/conf/autopartition-long.txt:ro
      - ./config/partition-hash-int.txt:/mycat/conf/partition-hash-int.txt:ro
      - ./logs/:/mycat/logs/:rw