version: "3"

services:
  demo_server_php_swoole_udp:
    image: php-swoole-8048:2.0.0
    container_name: demo_server_php_swoole_udp
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /data/demo_server_php_swoole_udp/www:/data/www
    ports:
      - "59503:9503"
    command: /bin/bash -c "php server_udp.php"
    networks:
      default:
        ipv4_address: 172.19.13.13

networks:
  default:
    external:
      name: docker_network