version: '3.1'

services:
  zookeeper_server:
    image: zookeeper:3.5.6
    restart: unless-stopped
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
    ports:
      - "52181:2181"
    container_name: zookeeper_container
  kafka_server:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "59092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 8.135.88.179
      KAFKA_ADVERTISED_PORT: 59092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper_server:2181"
      KAFKA_BROKER_ID: 1
      NUM_PARTITIONS: 5 # 默认分区数
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # 默认备份份数，仅指自动创建的topics
      KAFKA_CREATE_TOPICS: "MUSIC_SCORE:10:1,MUSIC_FEATURE:10:1"
    depends_on:
      - zookeeper_server
    container_name: kafka_container
  manager_server:
      image: sheepkiller/kafka-manager:latest
      restart: always
      container_name: manager_container
      ports:
        - "59000:9000"
      depends_on:
        - zookeeper_server
      environment:
        ZK_HOSTS: zookeeper_server:2181